### ISSUE TITLE
preliminary R bindings for simba

### ISSUE THREAD

**Issue by vjcitn** [pinellolab/simba#21]
A very preliminary view of simba-bioconductor interop is at https://vjcitn.github.io/Simba4Bioc/articles/Simba4Bioc.html ... if there is interest in collaborating on simplifying use within R, please let me know.

**Comment by huidongchen** [comment]
Hi, Thank you for taking the time to implement SIMBA in R—it's truly impressive!

I'd like to point out that SIMBA isn't accessible on PyPI due to specific dependency requirements and name unavailability. However, it is accessible through bioconda: https://bioconda.github.io/recipes/simba/README.html. You can easily install it using a single command `conda install simba`. Additionally, SIMBA v1.2 and the associated [documentation website](https://simba-bio.readthedocs.io/) are built on the repository at https://github.com/huidongchen/simba. SIMBA v1.2 encompasses all the functionalities showcased in the tutorials available at https://simba-bio.readthedocs.io/.

As I'm no longer working in the lab, my available time is limited for further contributions. However, there are others in the lab who can assist with the conversion.

**Comment by vjcitn** [comment]
Thanks for the update.
