### ISSUE TITLE
Query genes method not yielding expected behavior

### ISSUE THREAD

**Issue by daquang** [pinellolab/simba#7]
[SIMBA_MultiBatchCorrection (10).zip](https://github.com/pinellolab/simba/files/7591893/SIMBA_MultiBatchCorrection.10.zip)

I am replicating the SIMBA multi-batch example. Finding neighbor genes of given pins (cell 67 and beyond) is not yielding the expected behavior. I'm not sure if it is because I am using developer versions of SIMBa and SIMBA_pbg. I have attached a zip of my python notebook for reference.

**Comment by huidongchen** [comment]
The issue is that there are no neighbor genes of the given pin in your case and therefore it can not plot them. 

As the pytorch training procedure is not deterministic, the SIMBA embeddings of cells and genes from different runs are not exactly the same (although the structures are very similar). 

That being said, when specifying the pin on UMAP to look for the neighbor genes, you will need to check UMAP plot to make sure there are actually points within the range.

**Comment by daquang** [comment]
Thank you, I changed use_radius to False and now I'm getting results that make sense.
